import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8ea",
        outline: "#727783",
        "error-container": "#ffdad6",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#004f52",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#cbdddc",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#a1c9ff",
        "on-tertiary-fixed": "#0e1e1e",
        secondary: "#0b696d",
        "surface-container-low": "#f2f4f6",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c2c6d4",
        "inverse-primary": "#a1c9ff",
        "on-secondary-container": "#146d71",
        "on-primary-fixed-variant": "#004880",
        "secondary-fixed": "#a3eff4",
        tertiary: "#3a4a4a",
        "secondary-fixed-dim": "#87d3d7",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d2e4ff",
        primary: "#004981",
        "on-primary-fixed": "#001c37",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#1961a1",
        surface: "#f7f9fb",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#002021",
        "tertiary-fixed-dim": "#b8cac9",
        "primary-container": "#1b61a2",
        "inverse-on-surface": "#eff1f3",
        error: "#ba1a1a",
        "surface-dim": "#d8dadc",
        background: "#f7f9fb",
        "on-background": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "on-surface-variant": "#424752",
        "on-tertiary-fixed-variant": "#3a4a49",
        "surface-container": "#eceef0",
        "on-primary-container": "#c4dcff",
        "tertiary-container": "#526262",
        "secondary-container": "#a0edf1",
        "tertiary-fixed": "#d4e6e5",
        "on-surface": "#191c1e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
