import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        surface: "#f9f9f9",
        "on-tertiary-container": "#eaedff",
        "on-primary-fixed-variant": "#00419f",
        "error-container": "#ffdad6",
        "inverse-surface": "#2f3131",
        "on-surface-variant": "#424654",
        "surface-dim": "#dadada",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#524600",
        "on-error": "#ffffff",
        "surface-variant": "#e2e2e2",
        "secondary-fixed-dim": "#e4c600",
        primary: "#004cb9",
        "on-primary-fixed": "#001947",
        secondary: "#6d5e00",
        "on-background": "#1a1c1c",
        "surface-container": "#eeeeee",
        "on-primary-container": "#eaedff",
        "surface-bright": "#f9f9f9",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface": "#1a1c1c",
        "primary-container": "#1a64e3",
        "outline-variant": "#c2c6d7",
        "surface-container-high": "#e8e8e8",
        "tertiary-fixed-dim": "#b2c5ff",
        "secondary-fixed": "#ffe251",
        error: "#ba1a1a",
        "surface-container-low": "#f3f3f3",
        "primary-fixed": "#dae2ff",
        "inverse-primary": "#b1c5ff",
        "surface-container-lowest": "#ffffff",
        background: "#f9f9f9",
        "inverse-on-surface": "#f1f1f1",
        "secondary-container": "#fedc00",
        "surface-tint": "#0056d0",
        "on-secondary-container": "#706000",
        tertiary: "#2a4fa2",
        "on-tertiary-fixed-variant": "#184295",
        "on-tertiary-fixed": "#001848",
        "tertiary-container": "#4568bc",
        "primary-fixed-dim": "#b1c5ff",
        outline: "#737786",
        "tertiary-fixed": "#dae2ff",
        "on-secondary-fixed": "#211b00",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
